# Generated by Django 4.1.5 on 2023-06-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resim',
            field=models.FileField(null=True, upload_to='product/'),
        ),
    ]
